spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    properties:
      schema: "usernvbs"
  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:postgres}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    change-log: classpath:db.migration/db.changelog-master.yaml
    liquibase-schema: "notification"
    enabled: true
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5675}
    username: ${RABBIT_USERNAME:spring-webflux}
    password: ${RABBIT_PASSWORD:spring-webflux}
    exchange: exchange.direct.webflux
  profiles:
    active: dev
  application:
    name: notification-service
  mail:
    host: smtp.mail.ru
    port: 587
    username: saydaliyevelmurod01@gmail.ru
    password: Gmcz6tUCHdF9bzPbKgpf
    properties:
      mail:
        smtp:
          auth: true
        starttls:
          enable: true




springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


server:
  port:
