spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:postgres}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:postgres}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    change-log: classpath:db.migration/db.changelog-master.yaml
    liquibase-schema: "users"
    enabled: true
  profiles:
    active: dev
  application:
    name: my-app


springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


application:
  token:
    signing:
      key: 7C7P662RQS6JXHJL3VEK8ZJU0VHU4KZ2JXYJ8LZOCYHV591S97SL32HFZMADCVI2
server:
  port: 8081