server:
  port: 8201

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost:5436}/${DATABASE_NAME:postgres-test?schema=users}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    properties:
      schema: users

  data:
    redis:
      host: localhost
      port: 6379
      password: M1msoFt



  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:M1msoftR@bb!t}
    password: ${RABBIT_PASSWORD:M1msoftR@bb!t}
    exchange: exchange.direct.lamenu

  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5436}/${DATABASE_NAME:postgres-test}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    change-log: classpath:db/migration/changelog-master.yaml
    liquibase-schema: "users"
    enabled: true


logging:
  level:
    org.example: info
    org.springframework.security: info