version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: postgres-webflux
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "${DATABASE_PORT}:${DATABASE_PORT}"

  user-service:
    image: user-service:latest
    build:
      context: .
      dockerfile: ./services/user/Dockerfile
    ports:
      - "8081:8081"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./services/user/build/libs/user-0.0.1-SNAPSHOT.jar:/app/user-0.0.1-SNAPSHOT.jar

  notification-service:
    image: notification-service:latest
    build:
      context: .
      dockerfile: ./services/notification/Dockerfile
    ports:
      - "8082:8082"
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_PORT: ${DATABASE_PORT}
    volumes:
      - ./services/notification/build/libs/notification-0.0.1-SNAPSHOT.jar:/app/notification-0.0.1-SNAPSHOT.jar


volumes:
  postgres_volume:
