spring:
  application:
    name: bot-service
  config:
    import: "optional:configserver:http://localhost:8088"

  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost:5434}/${DATABASE_NAME:postgres?schema=bot}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    properties:
      schema: bot

  data:
    redis:
      host: localhost
      port: 6379
      password: M1msoFt



  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:M1msoftR@bb!t}
    password: ${RABBIT_PASSWORD:M1msoftR@bb!t}
    exchange: exchange.direct.lamenu

  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5434}/${DATABASE_NAME:postgres?schema=bot}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    change-log: classpath:db/migration/changelog-master.yaml
    liquibase-schema: "bot"
    enabled: true


logging:
  level:
    org.example: info
    org.springframework.security: info
server:
  port: 8202



