server:
  port: 8119
  forward-headers-strategy: framework
  servlet:
    contextPath: /
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: webbot-service

  batch:
    jdbc:
      initialize-schema: always

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5436}/${DATABASE_NAME:postgres-test}
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate
      open-in-view: false
    properties:
      hibernate:
        default_schema: exam
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          lob:
            non_contextual_creation: true

  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5436}/${DATABASE_NAME:postgres-test}
    user: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:secret}
    change-log: classpath:db/migration/changelog-master.yaml
    liquibase-schema: exam
    enabled: true

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:M1msoftR@bb!t}
    password: ${RABBIT_PASSWORD:M1msoftR@bb!t}
    exchange: exchange.direct.lamenu

  codec:
    max-in-memory-size: 16MB

  servlet:
    multipart:
      max-file-size: 16MB


#  cache:
#    type: redis




springdoc:
  api-docs:
    path: /api/exam/v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


info:
  app:
    name: ${spring.application.name}
    version: "@application.version@"
    description: "@application.description@"

