spring:
  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:spring-webflux}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
  liquibase:
    url: jdbc:postgresql://${DATABASE_HOST:localhost:5430}/${DATABASE_NAME:spring-webflux}
    user: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    change-log: classpath:db/migration/changelog-master.yaml
    liquibase-schema: "users"
    enabled: true
  batch:
    jdbc:
      initialize-schema: always
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    hibernate:
      ddl-auto: validate # Apply missing Flyway scripts to DB, and validate if JPA and DB model match during startup
    # https://stackoverflow.com/questions/30549489/what-is-this-spring-jpa-open-in-view-true-property-in-spring-boot
    open-in-view: false
    properties:
      hibernate:
        default_schema: users
        enable_lazy_load_no_trans: true
        event:
          merge:
            entity_copy_observer: allow
        jdbc:
          lob:
            non_contextual_creation: true
        connection:
          pool_size: 20
  profiles:
    active: dev
  application:
    name: user-service

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html

server:
  port: ${AUTH_SERVICE_PORT:8082}


app:
  security:
    jwt:
      secret-key: 7C7P662RQS6JXHJL3VEK8ZJU0VHU4KZ2JXYJ8LZOCYHV591S97SL32HFZMADCVI2
      access-expiration: 123
      refresh-expiration: 1
      confirmation-expiration: 1
logging:
  level:
    org.springframework.r2dbc.core: DEBUG