spring:
  application:
    name: download-service
  config:
    import: "optional:configserver:http://localhost:8088"




  r2dbc:
    url: r2dbc:postgresql://${DATABASE_HOST:localhost:5436}/${DATABASE_NAME:postgres-test?schema=users}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:secret}
    properties:
      schema: users

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USERNAME:M1msoftR@bb!t}
    password: ${RABBIT_PASSWORD:M1msoftR@bb!t}
    exchange: exchange.direct.lamenu
server:
  port: 8201

logging:
  level:
    org.example: info
    org.springframework.security: info



